spring:
  security:
    oauth2:
      client:
        provider:
          nextjs:
            issuer-uri: http://localhost:8080
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
          telegram:
            authorization-uri: https://oauth.telegram.org/auth
            token-uri: https://oauth.telegram.org/access_token
            user-info-uri: https://api.telegram.org/user
        registration:
          nextjs:
            provider: nextjs
            client-id: nextjs
            client-secret: nextjs123
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: http://localhost:8085/login/oauth2/code/nextjs
#          google:
#            provider: google
#            client-id: 1269394266-sqbgeggcmk05hop03kkggb3jfi6tb5lf.apps.googleusercontent.com
#            client-secret: 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
#            authorization-grant-type: authorization_code
#            scope: openid, profile, email
#            redirect-uri: http://localhost:8085/login/oauth2/code/google
          github:
            provider: github
            client-id: Ov23liZp7jXgv2WZShWi
            client-secret: 2c0592220b43a3442cd89478dd75ffa3357936f2
            authorization-grant-type: authorization_code
            scope: user:email
            redirect-uri: http://localhost:8085/login/oauth2/code/github
          telegram:
            provider: telegram
            client-id: telegram
            client-secret: telegram-secret
            authorization-grant-type: authorization_code
            scope: profile
            redirect-uri: http://localhost:8085/login/oauth2/code/telegram

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: business-route
          uri: lb://business
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - TokenRelay=
            - RewritePath=/categories/(?<segment>.*),/$\{segment}

        - id: identity-route
          uri: lb://identity
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

        - id: nextjs
          uri: http://localhost:3000  # Next.js frontend URL
          predicates:
            - Path=/**
          filters:
            - TokenRelay=
#            - RewritePath=/**,/$\{segment}
