spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  application:
    name: business
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

twilio.accountSid: ACb04e32f728caa95ac378c96025413050
twilio.authToken: 7a25c38e73e2edc907e159eb838b8524
twilio.phoneNumber: 0718442020
