spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1269394266-sqbgeggcmk05hop03kkggb3jfi6tb5lf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

  application:
    name: identity
  profiles:
    active: dev

  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
    stream:
      kafka:
        binder:
          brokers: 143.198.83.9:9092
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
server:
  port: 8080
